apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: rolebinding-pol
spec:  
  object-templates-raw: |
    - complianceType: mustonlyhave
      objectDefinition:
        kind: RoleBinding
        apiVersion: rbac.authorization.k8s.io/v1
        metadata:
          name: avanzato-view
          namespace: default
        subjects:
          - kind: Group
            apiGroup: rbac.authorization.k8s.io
            name: adminz
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: view
  pruneObjectBehavior: DeleteIfCreated
  remediationAction: inform
  severity: medium
